from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from decimal import Decimal

from trading_bot.data.models import Bar, Quote, Trade
from trading_bot.monitoring.event_logger import EventLogger


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    Represents a trading decision made by a strategy that should
    be executed by the order manager.
    """
    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    quantity: Optional[Decimal] = None
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate signal."""
        if self.action not in ('buy', 'sell', 'hold'):
            raise ValueError(f"Invalid action: {self.action}")
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if self.action != 'hold' and self.quantity is not None:
            if self.quantity <= 0:
                raise ValueError(f"Quantity must be positive, got {self.quantity}")

    def __repr__(self) -> str:
        return (
            f"Signal({self.symbol} {self.action} "
            f"{self.quantity if self.quantity else ''} "
            f"conf={self.confidence:.2f})"
        )


class BaseStrategy(ABC):
    """Base class for all trading strategies.

    Strategies inherit from this class and implement methods to process
    market data and generate trading signals.
    """

    def __init__(self, name: str, config: Dict[str, Any], event_logger: Optional[EventLogger] = None):
        """Initialize strategy.

        Args:
            name: Strategy name
            config: Strategy configuration parameters
            event_logger: Optional event logger for tracking decisions
        """
        self.name = name
        self.config = config
        self.event_logger = event_logger
        self.positions = {}
        self._signals_generated = 0
        self._bars_processed = 0

        # Extract filters from config (optional)
        self.filters = config.get('filters', {})
        self._filter_skipped_count = 0

        # Price history tracking for strategy warm-up and indicator calculations
        # These can be populated by the strategy warmer with historical data
        self.price_history = {}  # {symbol: [close_prices...]}
        self.high_history = {}   # {symbol: [high_prices...]}
        self.low_history = {}    # {symbol: [low_prices...]}
        self.volume_history = {} # {symbol: [volumes...]}

    def should_trade(self, bar: Bar) -> bool:
        """Check if trading should occur based on filters.

        Default implementation checks common filters. Override to customize.

        Args:
            bar: Bar data to check filters against

        Returns:
            True if trading is allowed, False if filtered out.
        """
        # Check volume filter
        if 'min_volume' in self.filters:
            if bar.volume < self.filters['min_volume']:
                self._filter_skipped_count += 1
                if self.event_logger:
                    self.event_logger.log_filter_check(
                        symbol=bar.symbol,
                        strategy=self.name,
                        broker=self.config.get('broker', 'unknown'),
                        filter_name="Volume",
                        passed=False,
                        message=f"volume={bar.volume:.0f} < min={self.filters['min_volume']}",
                        details={"volume": bar.volume, "min_volume": self.filters['min_volume']},
                    )
                return False

        # Check volatility filters (subclasses should implement ATR calculation)
        # This is a hook for subclasses to implement
        if not self._check_volatility_filter(bar):
            self._filter_skipped_count += 1
            return False

        return True

    def _check_volatility_filter(self, bar: Bar) -> bool:
        """Check volatility-based filters.

        Override in subclasses to implement volatility filtering using ATR.

        Args:
            bar: Bar data

        Returns:
            True if volatility is acceptable, False if filtered out.
        """
        # Default: no volatility filter
        return True

    @abstractmethod
    def on_bar(self, bar: Bar) -> Optional[Signal]:
        """Process bar data and generate signal if applicable.

        Args:
            bar: Bar data

        Returns:
            Signal object or None if no signal.
        """
        pass

    @abstractmethod
    def on_quote(self, quote: Quote) -> Optional[Signal]:
        """Process quote data and generate signal if applicable.

        Args:
            quote: Quote data

        Returns:
            Signal object or None if no signal.
        """
        pass

    def on_trade(self, trade: Trade) -> Optional[Signal]:
        """Process trade data and generate signal if applicable.

        Default implementation returns None. Override to use trade data.

        Args:
            trade: Trade data

        Returns:
            Signal object or None if no signal.
        """
        return None

    def on_order_filled(self, order_id: str, fill_data: Dict[str, Any]) -> None:
        """Handle order fill event.

        Default implementation does nothing. Override to track position fills.

        Args:
            order_id: Order ID that was filled
            fill_data: Fill details
        """
        pass

    def on_position_update(self, position: Dict[str, Any]) -> None:
        """Handle position update event.

        Default implementation does nothing. Override to track positions.

        Args:
            position: Updated position data
        """
        pass

    @abstractmethod
    def validate_config(self) -> bool:
        """Validate strategy configuration.

        Should verify that all required parameters are present and valid.

        Returns:
            True if config is valid, False otherwise.
        """
        pass

    def get_position(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Get tracked position for symbol.

        Args:
            symbol: Stock symbol

        Returns:
            Position data or None if not tracked.
        """
        return self.positions.get(symbol)

    def update_position(self, symbol: str, position_data: Dict[str, Any]) -> None:
        """Update tracked position.

        Args:
            symbol: Stock symbol
            position_data: Position details to store
        """
        self.positions[symbol] = position_data
        self.on_position_update(position_data)

    def clear_position(self, symbol: str) -> None:
        """Clear tracked position.

        Args:
            symbol: Stock symbol
        """
        if symbol in self.positions:
            del self.positions[symbol]

    def record_signal(self, signal: Signal) -> None:
        """Record that a signal was generated.

        Args:
            signal: Generated signal
        """
        self._signals_generated += 1

    def record_bar(self) -> None:
        """Record that a bar was processed."""
        self._bars_processed += 1

    def get_stats(self) -> Dict[str, Any]:
        """Get strategy statistics.

        Returns:
            Dictionary with strategy stats.
        """
        return {
            'name': self.name,
            'bars_processed': self._bars_processed,
            'signals_generated': self._signals_generated,
            'filters_applied': bool(self.filters),
            'bars_filtered_out': self._filter_skipped_count,
            'bars_analyzed': self._bars_processed - self._filter_skipped_count,
            'signal_rate': (
                self._signals_generated / self._bars_processed
                if self._bars_processed > 0
                else 0
            ),
        }
